//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_CineBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ShowtimeID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public int TicketID { get; set; }
    
        public virtual Showtime Showtime { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
