//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_CineBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieRating
    {
        public MovieRating()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int RatedID { get; set; }
        public string RatedName { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
