//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_CineBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int MovieID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> RatedID { get; set; }
        public string Description { get; set; }
        public string Poster { get; set; }
        public Nullable<decimal> MovieScore { get; set; }
    
        public virtual MovieRating MovieRating { get; set; }
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
