//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_CineBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int PaymentMethodID { get; set; }
        public string PaymentMethodName { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
