//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_CineBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public Seat()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int SeatID { get; set; }
        public Nullable<int> ScreenID { get; set; }
        public string SeatName { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Screen Screen { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Status Status { get; set; }
    }
}
