//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_CineBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showtime
    {
        public Showtime()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ShowTimeID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> ScreenID { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Movie Movy { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
