//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_CineBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Users = new HashSet<User>();
            this.Bookings = new HashSet<Booking>();
            this.Seats = new HashSet<Seat>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
